# Generated by Django 4.1.7 on 2023-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('article_nr', models.IntegerField()),
                ('article_desc', models.CharField(max_length=255)),
                ('item_status', models.CharField(max_length=255)),
                ('UOM', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('category_desc', models.CharField(max_length=255)),
                ('class_id', models.IntegerField()),
                ('class_desc', models.CharField(max_length=255)),
                ('subclass_id', models.IntegerField()),
                ('subclass_desc', models.CharField(max_length=255)),
                ('brand_id', models.IntegerField()),
                ('brand_desc', models.CharField(max_length=255)),
                ('unitcost', models.FloatField()),
                ('supplier_id', models.IntegerField(null=True)),
                ('supplier_desc', models.CharField(max_length=255, null=True)),
                ('leadtime', models.FloatField()),
                ('minstock', models.IntegerField()),
                ('lotsitze', models.IntegerField()),
                ('actualstock', models.IntegerField()),
                ('undefined', models.CharField(max_length=255)),
                ('minorder_qty', models.IntegerField(null=True)),
            ],
        ),
    ]
