# Generated by Django 4.1.7 on 2023-04-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemaster',
            old_name='lotsitze',
            new_name='lotsize',
        ),
    ]
