# Generated by Django 4.1.7 on 2023-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0002_rename_lotsitze_articlemaster_lotsize'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlemaster',
            constraint=models.UniqueConstraint(fields=('article_nr', 'location_id'), name='unique_articlenr_locationid_combination'),
        ),
    ]
