# Generated by Django 4.1.7 on 2023-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0003_articlemaster_unique_articlenr_locationid_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_nr', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='actualstock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='article_nr',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='brand_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='brand_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='category_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='class_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='class_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='leadtime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='location_id',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='lotsize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='minstock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='subclass_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='subclass_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='undefined',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='unitcost',
            field=models.FloatField(null=True),
        ),
    ]
