# Generated by Django 4.1.7 on 2023-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0004_inbound_alter_articlemaster_actualstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemaster',
            name='article_nr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articlemaster',
            name='location_id',
            field=models.IntegerField(),
        ),
    ]
