# Generated by Django 4.1.7 on 2023-04-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repex', '0005_alter_articlemaster_article_nr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('location_id', models.IntegerField()),
                ('passengers', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='passengernumbers',
            constraint=models.UniqueConstraint(fields=('date', 'location_id'), name='unique_date_locationid_combination'),
        ),
    ]
